apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: recipe-app-api
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./deploy/k8s/django
  prune: true
  sourceRef:
    kind: GitRepository
    name: recipe-app-api
