kind: Service
apiVersion: v1
metadata:
  name: django-service
  namespace: default
spec:
  selector:
    pod: django
  ports:
  - protocol: TCP
    port: 80
    targetPort: django-port
  type: NodePort
